### ISSUE TITLE
CI: confused pipeline 😕  !!

### ISSUE THREAD

**Issue by 3imed-jaberi** [gayanvoice/nodejs-graphql#27]
Hi @gayanvoice, I found config for more than one CI platform .. and this doesn't look good .. so please choose one platform. !!

**Comment by gayanvoice** [comment]
What is your suggestion between Travis and CircleCI?

**Comment by 3imed-jaberi** [comment]
> What is your suggestion between Travis and CircleCI?

In fact, the two are awesome, but I recommend Travis CI, as it is easier to handle.
